/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ConexionBD;
import java.sql.*;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 * Ventana para realizar el registro
 * @author Mario
 */
public class VentanaRegistro extends javax.swing.JFrame {

    private ConexionBD conexion;
    private Connection con;

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro() {
        initComponents();
        jPanel4.setVisible(false);
        buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(botonCliente);
        buttonGroup1.add(botonEmpleado);
        setTitle("Registro");
        setLocationRelativeTo(null);
        checkBoxContrasenia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (checkBoxContrasenia.isSelected()) {
                    textoContrasenia.setEchoChar('\u0000');
                } else {
                    textoContrasenia.setEchoChar('\u2022');
                }
            }
        });
        botonCliente.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (botonCliente.isSelected()) {
                    jScrollPane1.setVisible(true);
                    comboBoxEmpleados.setVisible(false);
                    jPanel4.setVisible(true);
                } else {
                    comboBoxEmpleados.setVisible(true);
                    jPanel4.setVisible(false);
                }
            }
        });
        botonEmpleado.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (botonEmpleado.isSelected()) {
                    jScrollPane1.setVisible(false);
                    comboBoxEmpleados.setVisible(true);
                    jPanel4.setVisible(true);
                } else {
                    jScrollPane1.setVisible(true);
                    jPanel4.setVisible(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textoApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoTelf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textoCuenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textoContrasenia = new javax.swing.JPasswordField();
        botonCliente = new javax.swing.JRadioButton();
        botonEmpleado = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDescripcion = new javax.swing.JTextArea();
        comboBoxEmpleados = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        checkBoxContrasenia = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();

        jCheckBox1.setBackground(new java.awt.Color(18, 189, 201));
        jCheckBox1.setText("mostrarContraseña");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRARSE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        textoApellidos.setForeground(new java.awt.Color(204, 204, 204));
        textoApellidos.setText("Introduce tus apellidos");
        textoApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoApellidosFocusLost(evt);
            }
        });
        textoApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApellidosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos:");

        textoEmail.setForeground(new java.awt.Color(204, 204, 204));
        textoEmail.setText("ejemplo@ejemplo.com");
        textoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoEmailFocusLost(evt);
            }
        });
        textoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEmailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email:");

        textoNombre.setForeground(new java.awt.Color(204, 204, 204));
        textoNombre.setText("Introduce tu nombre");
        textoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoNombreFocusLost(evt);
            }
        });
        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Teléfono:");

        textoTelf.setForeground(new java.awt.Color(204, 204, 204));
        textoTelf.setText("Telefono");
        textoTelf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoTelfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoTelfFocusLost(evt);
            }
        });
        textoTelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTelfActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Cuenta:");

        textoCuenta.setForeground(new java.awt.Color(204, 204, 204));
        textoCuenta.setText("Introduce tu cuenta nueva");
        textoCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoCuentaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoCuentaFocusLost(evt);
            }
        });
        textoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCuentaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Contraseña:");

        textoContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseniaActionPerformed(evt);
            }
        });

        botonCliente.setText("Cliente");
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });

        botonEmpleado.setText("Empleado");
        botonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpleadoActionPerformed(evt);
            }
        });

        jPanel4.setOpaque(false);

        textoDescripcion.setColumns(20);
        textoDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        textoDescripcion.setRows(5);
        textoDescripcion.setText("Añade una descripcion de ti");
        textoDescripcion.setOpaque(false);
        textoDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoDescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoDescripcionFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(textoDescripcion);

        comboBoxEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peluquero", "Esteticien", "Manicurista" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxEmpleados, 0, 81, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(comboBoxEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setText("Selecciona como deseas registrarte:");

        checkBoxContrasenia.setText("mostrarContraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(textoApellidos))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(botonCliente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCuenta)
                                    .addComponent(textoContrasenia)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(botonEmpleado))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkBoxContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(textoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(textoTelf)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(138, 138, 138)))
                .addGap(82, 82, 82))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEmpleado)
                    .addComponent(botonCliente))
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleDescription("");
        textoEmail.getAccessibleContext().setAccessibleName("");
        jLabel5.getAccessibleContext().setAccessibleDescription("");
        textoContrasenia.getAccessibleContext().setAccessibleName("");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel6.setOpaque(false);

        botonAceptar.setText("ACEPTAR");
        botonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new java.awt.GridBagConstraints());

        jPanel7.setOpaque(false);

        botonCancelar.setText("CANCELAR");
        botonCancelar.setMaximumSize(new java.awt.Dimension(83, 25));
        botonCancelar.setMinimumSize(new java.awt.Dimension(83, 25));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonCancelar.getAccessibleContext().setAccessibleDescription("");

        jPanel5.add(jPanel7, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCuentaActionPerformed

    private void textoTelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTelfActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    private void textoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEmailActionPerformed

    private void textoApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApellidosActionPerformed

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonClienteActionPerformed

    private void botonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEmpleadoActionPerformed

    private void textoDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDescripcionFocusGained
        // TODO add your handling code here:
        if (textoDescripcion.getText().contains("Añade una descripcion de ti")) {
            textoDescripcion.setText("");
            textoDescripcion.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textoDescripcionFocusGained

    private void textoDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDescripcionFocusLost
        // TODO add your handling code here:
        if (textoDescripcion.getText().isEmpty()) {
            textoDescripcion.setForeground(Color.GRAY);
            textoDescripcion.setText("Añade una descripcion de ti");
        }
    }//GEN-LAST:event_textoDescripcionFocusLost

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if (comprobarCamposVacios() == false || comprobarTelefono() == false || comprobarEmail() == false) {
        } else {
            insertarUsuario();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void insertarUsuario() throws NumberFormatException, HeadlessException {
        String usuario = textoCuenta.getText();
        try {
            con = ConexionBD.conectarSinLogin();
            String sql = "SELECT * FROM USUARIO WHERE CUENTA LIKE ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, textoCuenta.getText());
            ResultSet rs = ps.executeQuery();
            if (!rs.next()) {
                if (botonCliente.isSelected()) {
                    try {
                        insertarUsuarioCliente();
                        insertarCliente();
                        JOptionPane.showMessageDialog(null, "Cliente registrado", "Insercion completada", JOptionPane.DEFAULT_OPTION);
                        VentanaLog vl = new VentanaLog();
                        vl.setVisible(true);
                        dispose();

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado en la inserción");
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Error en el formato del telefono. ¿Ha puesto algun caracter que no sea numerico?");
                    }
                }
                if (botonEmpleado.isSelected()) {
                    try {
                        insertarUsuarioPersonal();
                        insertarPersonal();
                        JOptionPane.showMessageDialog(null, "Empleado registrado", "Insercion completada", JOptionPane.DEFAULT_OPTION);
                        VentanaLog vl = new VentanaLog();
                        vl.setVisible(true);
                        dispose();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado en la inserción");
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Error en el formato del telefono. ¿Ha puesto algun caracter que no sea numerico?");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario ya existe, por favor introduce un usuario que esté disponible");
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void insertarPersonal() throws SQLException {
        String insercionPersonal = "INSERT INTO PERSONAL(ID,TIPO) VALUES (?,?)";
        PreparedStatement psPersonal = con.prepareStatement(insercionPersonal);
        int idC = consultarIdUsuario();
        psPersonal.setInt(1, idC);
        psPersonal.setString(2, comboBoxEmpleados.getSelectedItem().toString());
        psPersonal.executeUpdate();
        psPersonal.close();
    }

    private void insertarUsuarioPersonal() throws NumberFormatException, SQLException {
        String insercionUsuarioPersonal = "INSERT INTO USUARIO (NOMBRE,APELLIDOS,EMAIL,TELEFONO,CUENTA,CONTRASENIA,TIPO_DE_USUARIO) VALUES (?,?,?,?,?,?,?)";
        PreparedStatement psUsuario = con.prepareStatement(insercionUsuarioPersonal);
        psUsuario.setString(1, textoNombre.getText());
        psUsuario.setString(2, textoApellidos.getText());
        psUsuario.setString(3, textoEmail.getText());
        psUsuario.setInt(4, Integer.parseInt(textoTelf.getText()));
        psUsuario.setString(5, textoCuenta.getText());
        psUsuario.setString(6, textoContrasenia.getText().toString());
        psUsuario.setString(7, "Personal");
        psUsuario.executeUpdate();
    }

    private void insertarCliente() throws SQLException {
        String insercionCliente = "INSERT INTO CLIENTE(ID,DESCRIPCION) VALUES (?,?)";
        PreparedStatement psCliente = con.prepareStatement(insercionCliente);
        int idC = consultarIdUsuario();
        psCliente.setInt(1, idC);
        psCliente.setString(2, textoDescripcion.getText());
        psCliente.executeUpdate();
        psCliente.close();
    }

    private int consultarIdUsuario() throws SQLException {
        String consultarId = "SELECT ID FROM USUARIO WHERE CUENTA LIKE ?";
        int idUsuario = -1;
        PreparedStatement cogerId = con.prepareStatement(consultarId);
        cogerId.setString(1, textoCuenta.getText());
        ResultSet rsId = cogerId.executeQuery();
        while (rsId.next()) {
            idUsuario = rsId.getInt("ID");
        }
        rsId.close();
        return idUsuario;
    }

    private void insertarUsuarioCliente() throws SQLException, NumberFormatException {
        String insercionUsuario = "INSERT INTO USUARIO (NOMBRE,APELLIDOS,EMAIL,TELEFONO,CUENTA,CONTRASENIA,TIPO_DE_USUARIO) VALUES (?,?,?,?,?,?,?)";
        PreparedStatement psUsuario = con.prepareStatement(insercionUsuario);
        psUsuario.setString(1, textoNombre.getText());
        psUsuario.setString(2, textoApellidos.getText());
        psUsuario.setString(3, textoEmail.getText());
        psUsuario.setInt(4, Integer.parseInt(textoTelf.getText()));
        psUsuario.setString(5, textoCuenta.getText());
        psUsuario.setString(6, textoContrasenia.getText().toString());
        psUsuario.setString(7, "Cliente");
        psUsuario.executeUpdate();
    }

    private boolean comprobarEmail() throws HeadlessException {
        if (!textoEmail.getText().matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")) {
            JOptionPane.showMessageDialog(null, "Email no valido");
            return false;
        } else {
            return true;
        }
    }

    private boolean comprobarTelefono() throws HeadlessException {
        if (textoTelf.getText().length() != 9) {
            JOptionPane.showMessageDialog(null, "Telefono no valido. Introduce 9 digitos");
            return false;
        } else {
            return true;
        }
    }

    private boolean comprobarCamposVacios() throws HeadlessException {
        // TODO add your handling code here:
        if (textoApellidos.getText().isEmpty() || textoNombre.getText().isEmpty() || textoContrasenia.getText().isBlank() || textoCuenta.getText().isEmpty() || textoDescripcion.getText().isEmpty() || textoEmail.getText().isEmpty() || textoTelf.getText().isEmpty() || buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Faltan campos");
            return false;
        } else {
            return true;
        }
    }

    private void textoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoNombreFocusGained
        // TODO add your handling code here:
        if (textoNombre.getText().contains("Introduce tu nombre")) {
            textoNombre.setText("");
            textoNombre.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textoNombreFocusGained

    private void textoContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraseniaActionPerformed

    private void textoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoNombreFocusLost
        // TODO add your handling code here:
        if (textoNombre.getText().isEmpty()) {
            textoNombre.setForeground(Color.GRAY);
            textoNombre.setText("Introduce tu nombre");
        }
    }//GEN-LAST:event_textoNombreFocusLost

    private void textoApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoApellidosFocusGained
        // TODO add your handling code here:
        if (textoApellidos.getText().contains("Introduce tus apellidos")) {
            textoApellidos.setText("");
            textoApellidos.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textoApellidosFocusGained

    private void textoApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoApellidosFocusLost
        // TODO add your handling code here:
        if (textoApellidos.getText().isEmpty()) {
            textoApellidos.setForeground(Color.GRAY);
            textoApellidos.setText("Introduce tus apellidos");
        }
    }//GEN-LAST:event_textoApellidosFocusLost

    private void textoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoEmailFocusGained
        // TODO add your handling code here:
        if (textoEmail.getText().contains("ejemplo@ejemplo.com")) {
            textoEmail.setText("");
            textoEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textoEmailFocusGained

    private void textoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoEmailFocusLost
        // TODO add your handling code here:
        if (textoEmail.getText().isEmpty()) {
            textoEmail.setForeground(Color.GRAY);
            textoEmail.setText("ejemplo@ejemplo.com");
        }
    }//GEN-LAST:event_textoEmailFocusLost

    private void textoTelfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoTelfFocusGained
        // TODO add your handling code here:
        if (textoTelf.getText().contains("Telefono")) {
            textoTelf.setText("");
            textoTelf.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textoTelfFocusGained

    private void textoTelfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoTelfFocusLost
        // TODO add your handling code here:
        if (textoTelf.getText().isEmpty()) {
            textoTelf.setForeground(Color.GRAY);
            textoTelf.setText("Telefono");
        }
    }//GEN-LAST:event_textoTelfFocusLost

    private void textoCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoCuentaFocusGained
        // TODO add your handling code here:
        if (textoCuenta.getText().contains("Introduce tu cuenta nueva")) {
            textoCuenta.setText("");
            textoCuenta.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textoCuentaFocusGained

    private void textoCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoCuentaFocusLost
        // TODO add your handling code here:
        if (textoCuenta.getText().isEmpty()) {
            textoCuenta.setForeground(Color.GRAY);
            textoCuenta.setText("Introduce tu cuenta nueva");
        }
    }//GEN-LAST:event_textoCuentaFocusLost

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        int decision = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cancelar la operacion?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
        switch (decision) {
            case JOptionPane.YES_OPTION:
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                break;
            case JOptionPane.CANCEL_OPTION:
                break;
        }

    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JRadioButton botonCliente;
    private javax.swing.JRadioButton botonEmpleado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxContrasenia;
    private javax.swing.JComboBox<String> comboBoxEmpleados;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JPasswordField textoContrasenia;
    private javax.swing.JTextField textoCuenta;
    private javax.swing.JTextArea textoDescripcion;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelf;
    // End of variables declaration//GEN-END:variables
}
